[project]
name = "algo5"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pandas>=2.0","pyarrow>=14.0"]
[project.optional-dependencies]
dev = ["pre-commit", "ruff", "black", "mypy", "pytest"]


[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]

[tool.mypy]
python_version = "3.12"
mypy_path = "src"
explicit_package_bases = true
files = ["src", "tests"]          # <-- sadece bunları tara
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
pretty = true
