[project]
name = "algo5"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pandas>=2.0","pyarrow>=14.0"]
[project.optional-dependencies]
test = ["pytest>=8.0","pytest-cov>=6.0"]
[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
