[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "algo5"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["pandas>=2.0", "pyarrow>=12"]

[project.optional-dependencies]
test = ["pytest>=7.4", "pytest-cov>=4.1"]
ui = ["streamlit>=1.28"]
