name: ci

on:
  pull_request:
  push:
    branches: [ main, "feature/**", "week-*/**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - name: Install package + dev deps
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
          pip install pytest pytest-cov pre-commit

      - name: Pre-commit (ruff/black/mypy)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Pytest (ignore vendored)
        run: pytest -q --ignore=third_party --cov=src --cov-report=xml --cov-report=term-missing

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
