name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # proje bağımlılıkları
          pip install -e . || true
          # CI araçları
          pip install pytest pytest-cov ruff black pre-commit

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Run pre-commit hooks (repo rules)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests (+ coverage)
        run: |
          pytest -q --junitxml=reports/junit.xml --cov=src --cov-report=xml

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python }}
          path: |
            reports/junit.xml
            coverage.xml
