$ci = @"
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test (3.12)
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest pytest-cov mypy genbadge[coverage]

      - name: Typecheck (mypy)
        run: mypy

      - name: Test + Coverage
        env:
          COV_MIN: 79.5
          BRANCH_MIN: 50
        run: |
          pytest -q --ignore=third_party --maxfail=1 --disable-warnings \
            --cov=src --cov-branch --cov-report=xml:coverage.xml \
            --cov-fail-under=${{ env.COV_MIN }}

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml

      - name: Generate coverage badge (SVG)
        run: |
          mkdir -p .github/badges
          genbadge coverage -i coverage.xml -o .github/badges/coverage.svg

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/badges/coverage.svg
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText(".github/workflows/ci.yml", $ci, $utf8NoBom)
