name: perf

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: perf smoke
        run: echo "perf ok"
