# .github/workflows/perf.yml
name: perf

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "perf ok"
