name: pr-body-check
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  require-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.pull_request.body || "").toLowerCase();
            const ok = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#\d+/.test(body);
            if (!ok) {
              core.setFailed("PR body must reference an issue, e.g. 'Closes #6'.");
            }
